# Generated by Django 5.2.8 on 2025-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
