# Generated by Django 5.2.8 on 2025-11-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Premium (Monthly)'), ('annual', 'Premium (Annual)')], default='free', max_length=20),
        ),
    ]
