# Generated by Django 5.2.8 on 2025-11-19 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('asset_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='session',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='session',
            name='script_text',
        ),
        migrations.AddField(
            model_name='session',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='session',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='pre_session_mood',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='session',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='session',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='selected_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='session',
            name='voice',
            field=models.CharField(default='Calm female voice', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='session',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meditation.background'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meditation.mood'),
        ),
        migrations.CreateModel(
            name='MoodQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meditation.mood')),
            ],
        ),
    ]
