# Generated by Django 5.2.8 on 2025-11-19 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0002_background_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mood',
            field=models.CharField(default='stress', max_length=50),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='session',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_downloaded',
        ),
        migrations.RemoveField(
            model_name='session',
            name='pre_session_mood',
        ),
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Playback/download URL for generated audio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='background',
            field=models.CharField(default='ocean', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(default=15, help_text='Session duration in minutes (always 15)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Marked true after user finishes and rates session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='rating',
            field=models.IntegerField(blank=True, help_text='User rating from 1–5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='script',
            field=models.TextField(blank=True, help_text='Generated meditation script'),
        ),
        migrations.AlterField(
            model_name='session',
            name='selected_answers',
            field=models.JSONField(default=dict, help_text='Stores answers as {question_text: selected_option}'),
        ),
        migrations.AlterField(
            model_name='session',
            name='voice',
            field=models.CharField(default='female', help_text='Voice used for meditation narration', max_length=50),
        ),
        migrations.DeleteModel(
            name='MoodQuestion',
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
