# Generated by Django 5.2.8 on 2025-11-22 04:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0003_alter_session_mood_remove_rating_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='background',
            name='asset_url',
        ),
        migrations.AddField(
            model_name='background',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='background',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='background',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='selected_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='voice',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Voice used for meditation narration', max_length=10),
        ),
        migrations.CreateModel(
            name='MoodQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meditation.mood')),
            ],
            options={
                'ordering': ['mood', 'created_at'],
            },
        ),
    ]
