# Generated by Django 5.2.8 on 2025-11-18 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mindfulness_goal', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=100, null=True)),
                ('meditation_time', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=50, null=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('subscription_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
